module.exports = [
  {
    name: "Michael Hoffmann (Mokkapps)",
    description: "🌴 Freelancer | 👨🏻‍💻 Developer | ✍️ Blogger",
    url: "https://mokkapps.de/blog/",
    tags: [
      "JavaScript",
      "TypeScript",
      "Node.js",
      "Express.js",
      "Git",
      "Tech",
      "Frontend",
      "Fullstack",
      "HTML",
      "CSS",
      "Gatsby",
      "Spring Boot",
      "Backend",
      "Freelancing",
      "Career",
      "Software Development",
    ],
  },
  {
    name: "Alula Kibrom",
    description: "Fullstack Developer | Entrepreneur | Blogger",
    url: "https://businesstyc.com/blog/",
    twitter: "@altsyset",
    tags: [
      "JavaScript",
      "HTML",
      "CSS",
      "PHP",
      "Laravel",
      "Vue",
      "Angular",
      "Git",
    ],
  },
  {
    name: "Shravan Kumar",
    description:
      "Software Engineer | Bibliophilic | Generalizing Specialist | Curious Creature | I, sometimes write blog",
    url: "https://ohmyscript.com/",
    tags: [
      "JavaScript",
      "Python",
      "TypeScript",
      "Node.js",
      "Express.js",
      "Git",
      "Tech",
      "Backend",
      "Software Development",
      "Computer Science",
    ],
  },
  {
    name: "Shyam Manohar",
    description:
      "I'm a CS Under Grad who is passionate about sharing my ideas and experiences through blogs!",
    url: "https://xshyam.hashnode.dev",
    tags: ["Computer Science", "Tech", "Cybersecurity"],
  },
  {
    name: "Johnson-Awah Alfred",
    description:
      "Software engineer,Blockchain engineer, student, staff software engineer",
    url: "https://blog.codemon.me",
    tags: [
      "JavaScript",
      "Node.js",
      "React",
      "Computer Science",
      "PHP",
      "TypeScript",
    ],
  },
  {
    name: "William Chin",
    description:
      "Product Manager, Digital Marketer, Agile Consultant, Web Developer - Looking to make the world more digitally friendly one post at a time.",
    url: "https://yourdigitalaid.com/category/blog/",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "WordPress",
      "PHP",
      "SEO",
      "Digital Marketing",
      "Agile",
      "Scrum",
      "XP",
    ],
  },
  {
    name: "Kuldip Mochi",
    description: "Software engineer, full stack enthusiastic, student",
    url: "https://kuldipmochi.hashnode.dev/",
    tags: ["JavaScript", "Node.js", "React", "Computer Science"],
  },
  {
    name: "Peter Smith",
    description:
      "Networking, antique electrical bits, and more. Developer of multiple apps in the Window, including apps to control reverse-engineered Bluetooth devices. Wrote my first network program in 1989, slightly before the WWW.",
    url: "https://sunriseprogrammer.blogspot.com/",
    tags: ["Networking", "Bluetooth", "Programming Languages"],
  },
  {
    name: "Marko ⚡ Denic",
    description: "Web developer. IT consultant and trainer.",
    url: "https://markodenic.com/blog/",
    twitter: "@denicmarko",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Vue",
      "Nuxt",
      "Front End",
      "Laravel",
      "TailwindCSS",
      "SEO",
    ],
  },
  {
    name: "Suhail Kakar",
    description:
      "Full Stack Software Developer | Tech Blogger | Writes about JavaScript, Python, Open Source, and Software Development",
    url: "http://blog.suhailkakar.com/",
    twitter: "@SuhailKakar",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Software Development",
      "Open Source",
      "Front End",
      "Next",
      "Python",
      "SEO",
    ],
  },
  {
    name: "The Trojan",
    description:
      "I write about algorithmic solutions for Software Engineering problems, interesting programming tips & tricks. May also include Machine Learning and Blockchain",
    url: "https://apoorvtyagi.tech/",
    twitter: "@apoorv__tyagi",
    tags: [
      "Python",
      "Javascript",
      "Node.js",
      "Clean Code",
      "Backend",
      "Web Development",
      "Git",
      "Programming",
      "Computer Science",
    ],
  },
  {
    name: "Shaurya Pratap Singh",
    description: "A middle schooler who loves writing about programming.",
    url: "https://sblip.medium.com/",
    twitter: "@Shaurya79145816",
    tags: [
      "Python",
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Backend Development",
      "PostgreSQL",
      "Django",
      "Vue",
    ],
  },
  {
    name: "Karl Koch",
    description: "Product Designer and UI Developer.",
    url: "https://www.kejk.tech/thoughts",
    twitter: "@_kejk",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Vue",
      "Nuxt",
      "Swift",
      "SwiftUI",
      "Figma API",
      "Figma plugins",
      "Product design",
    ],
  },
  {
    name: "Shane Lee",
    description:
      "Staff engineer -  write about tech and sometimes sustainability 🌎",
    url: "https://blog.shanelee.name/",
    twitter: "@shavo27",
    tags: [
      "TypeScript",
      "Spring Boot",
      "Kubernetes",
      "React",
      "Docker",
      "Cloud native",
      "API first",
      "Tech",
      "AWS",
      "Cloud infra",
    ],
  },
  {
    name: "Akanksha Raghav",
    description:
      "A tech enthusiast who enjoy exploring new technologies and leverage them to solve real-life problem",
    url: "https://akanksharaghav.medium.com/",
    twitter: "@akanksharaghav9",
    tags: ["Voice user Interface", "Javascript", "Hosting", "Github", "MERN"],
  },
  {
    name: "Peter Witham",
    description: "Swift and Apple development articles",
    url: "https://compileswift.com/journal/",
    twitter: "@compileswift",
    tags: ["Swift", "Objective-C", "SwiftUI"],
  },
  {
    name: "Tosin Fashanu",
    description: "Portfolio | Tutorial | Agency for web development.",
    url: "https://apluswebmaker.com",
    twitter: "@iamJohnFashanu",
    tags: [
      "JavaScript",
      "PHP",
      "React",
      "laravel",
      "Web Development",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "Olena Drugalya",
    description:
      "Olena is self-taught web developer and she writes her beginner-friendly and simply explained tech blogs along the way.",
    url: "https://olena.hashnode.dev/",
    twitter: "@OlenaDrugalya",
    tags: ["HTML", "CSS", "JavaScript", "Web Development", "React"],
  },
  {
    name: "Create React App Blog",
    description:
      "Stories About My Journey to Become a Developer. Overview of Best Web Dev Tools & Resources.",
    url: "https://create-react-app.com/",
    twitter: "@crapp_blog",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Front End",
      "React",
      "Productivity",
    ],
  },
  {
    name: "Abia Tech Hub",
    description: "Innovation | Technology | Entrepreneurship",
    url: "https://blog.abiatechhub.com",
    twitter: "@abiatechhub",
    tags: [
      "JavaScript",
      "Web Development",
      "React",
      "Web Components",
      "Chrome Extension",
      "Freelancing",
      "Mentorship",
      "WordPress",
      "Software Development",
      "Software Architecture",
    ],
  },
  {
    name: "Alberto Bonacina",
    description:
      "Proud Software Engineer, Flutter enthusiast and Free Software activist",
    url: "https://blog.albertobonacina.com/",
    twitter: "polilluminato",
    tags: [
      "Flutter",
      "Dart",
      "Android",
      "Linux",
      "Node.js",
      "APIs",
      "JavaScript",
      "Backend Development",
      "PostgreSQL",
    ],
  },
  {
    name: "hacking C++",
    description:
      "Learn Contemporary C++ // code examples, concise explanations and infographics",
    url: "https://hackingcpp.com",
    twitter: "@hackingcpp",
    tags: [
      "C++",
      "Software Development",
      "Software Engineering",
      "Algorithms",
      "Beginner",
    ],
  },
  {
    name: "Abdulmalik Adekunle",
    description: "Front End Web developer, Graphics Designer, IT consultant.",
    url: "https://abdulmalik.hashnode.dev",
    twitter: "@Emeritus_Ade",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "React",
      "Next.js",
      "Front End",
      "Node.js",
      "Bootstrap",
      "General Tech",
    ],
  },
  {
    name: "impure.fun",
    description: "Functional code for humans",
    url: "https://impure.fun",
    twitter: "@luwvis",
    tags: ["DDD", "F#", "Functional", ".NET"],
  },
  {
    name: "dubesar",
    description: "Python/JS Developer",
    url: "https://dubesar.hashnode.dev",
    twitter: "@Sarvesh12601156",
    tags: [
      "JavaScript",
      "Python",
      "C++",
      "Node.js",
      "Deep Learning",
      "Flask",
      "API",
      "UI Developer",
      "HTML",
      "CSS",
      "TailwindCSS",
    ],
  },
  {
    name: "C. Augusto Proiete",
    description:
      "Open-source maintainer: #cakebuild #serilog #exceldna #xlstack",
    url: "https://augustoproiete.net",
    twitter: "@augustoproiete",
    tags: [
      "Microsoft",
      ".NET",
      "C#",
      "Software Development",
      "Software Architecture",
      "Software Engineering",
      "Software Engineer",
      "CakeBuild",
      "Serilog",
      "XLStack",
    ],
  },
  {
    name: "Rahul",
    description: "Front-end Developer. Helping beginners in coding.",
    url: "https://rahulism.hashnode.dev",
    twitter: "@rahxul",
    tags: [
      "HTML",
      "CSS",
      "React",
      "Beginners",
      "Web Development",
      "JavaScript",
      "Front End",
      "Productivity",
    ],
  },
  {
    name: "Kévin Dunglas",
    description:
      "Kévin writes about the free software he uses and maintains. Most of the posts are about web APIs, Go, PHP and JavaScript.",
    url: "https://dunglas.fr",
    twitter: "@dunglas",
    tags: [
      "APIs",
      "Go",
      "PHP",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Symfony",
      "API Platform",
      "Web Development",
    ],
  },
  {
    name: "Rahul Banerjee",
    description:
      "An average Computer Engineering Student who writes How-to tutorials on different technologies",
    url: "https://www.realpythonproject.com/",
    twitter: "@rahulbanerjee99",
    tags: [
      "Software Developer",
      "Python",
      "APIs",
      "Machine Learning",
      "Data Science",
      "C++",
      "SQL",
      "Data Base",
      "Data Engineering",
    ],
  },
  {
    name: "Sunil Sandhu",
    description: "Software Developer, Founder of In Plain English",
    url: "https://sunilsandhu.com/",
    twitter: "@sunilsandhu",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Vue",
      "React",
      "Front End",
      "Computer Science",
      "Algorithms",
      "Python",
    ],
  },
  {
    name: "Danny Steenman",
    description:
      "I’m an AWS Cloud Consultant who likes to build things in the Cloud. I write about my learnings on this Blog and on Twitter.",
    url: "https://towardsthecloud.com/",
    twitter: "@dannysteenman",
    tags: ["AWS", "Certification", "Cloud", "Infrastructure", "Python"],
  },
  {
    name: "Jiri Tichy",
    description:
      "I’m helping companies fight technical debt and deliver better software faster. Our automated tool Codeac.io covers our back as well.",
    url: "https://www.codeac.io/blog/",
    twitter: "@tichy_jiri",
    tags: [
      "Clean Code",
      "Technical Debt",
      "Code Quality",
      "Infrastructure as Code",
      "Infrastructure",
      "Cloud Infrastructure",
      "Productivity",
      "Faster Development",
    ],
  },
  {
    name: "Phil McParlane",
    description:
      "Helping Software Developers get a job with a 4 day working week",
    url: "https://4dayweek.io/blog",
    twitter: "@philostar",
    tags: ["Career", "Self-Development", "Tech", "Jobs"],
  },
  {
    name: "Sam Larsen-Disney",
    description:
      "Sam currently works as a UX Engineer at American Express. He has built new ways to refer friends, onboarding experiences and rapid response systems.",
    url: "https://sld.codes/articles",
    twitter: "@SamLarsenDisney",
    tags: [
      "JavaScript",
      "Gatsby",
      "SCSS",
      "Front End",
      "Web Development",
      "React",
      "TailwindCSS",
      "UX Design",
    ],
  },
  {
    name: "Bhanu Teja Pachipulusu",
    description:
      "Full-Stack Developer, Entrepreneur and Co-Founder of Coderplex. Building https://coderplex.in. Checkout my portfolio at https://bhanuteja.dev",
    url: "https://blog.bhanuteja.dev",
    twitter: "@pbteja1998",
    tags: [
      "Web Development",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "GraphQL",
      "TailwindCSS",
      "Front End",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "Savio Martin",
    description:
      "A 13-year-old boy on an intention to enhance as a successful full-stack web developer. I love building full-stack web applications and mobile apps.",
    url: "https://savio.xyz/",
    twitter: "@saviomartin7",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Front End",
      "Node.js",
      "App Development",
      "React",
      "React Native",
      "UI/UX",
    ],
  },
  {
    name: "Sunil Kumar",
    description:
      "I write about how to become a better developer, AWS, freelancing & building SaaS products.",
    url: "https://sunilkumarc.in",
    twitter: "@sunilc_",
    tags: [
      "Web Development",
      "Freelancing",
      "Python",
      "Software Design",
      "Software Architecture",
      "AWS",
      "Infrastructure",
    ],
  },
  {
    name: "Alexander Rowsell",
    description: "Hardware hacker/embedded dev",
    url: "https://frozenelectronics.ca/",
    twitter: "@FrozenElecBlog",
    tags: [
      "Embedded",
      "Hardware hacker",
      "Canadian hacker",
      "C",
      "Assembly language",
    ],
  },
  {
    name: "Nat Miletic",
    description:
      "This blog covers a range of topics related to responsive web design, web development, and WordPress how-to guides.",
    url: "https://cliowebsites.com/blog/",
    twitter: "@natmiletic",
    tags: ["Web Design", "WordPress", "SEO"],
  },
  {
    name: "Alexander Lichter",
    description:
      "Nuxt.js maintainer and Web Development Consultant. I love to blog about various technical topics with a focus on web development, especially with Vue and Nuxt.",
    url: "https://blog.lichter.io/?ref=tech-blogs.dev",
    twitter: "@TheAlexLichter",
    tags: [
      "Nuxt",
      "Vue",
      "TailwindCSS",
      "JavaScript",
      "Web Development",
      "SEO",
      "Clean Code",
      "SSR",
      "Jamstack",
      "Refactoring",
    ],
  },
  {
    name: "Nacho Iacovino",
    description:
      "I'm a Frontend developer and Developer Relations. I share resources, tips and guides on web development. I like talking about best practices and new technologies. My favorite stack is Next.js and Tailwind CSS.",
    url: "https://nachoiacovino.com/blog",
    twitter: "@nachoiacovino",
    tags: [
      "TailwindCSS",
      "React",
      "Next.js",
      "Resources",
      "Front End",
      "JavaScript",
      "Web Development",
      "CSS",
      "HTML",
    ],
  },
  {
    name: "Ramya Chinnadurai (Rams)",
    description:
      "Full stack web developer. Passionate programmer and curious learner. Building http://100daysof.codes ",
    url: "http://ramyachinnadurai.in/",
    twitter: "@code_rams",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "React",
      "Node.js",
      "Chrome extensions",
      "Next.js",
    ],
  },
  {
    name: "Puru Vijay",
    description:
      "Fullstack Developer 6+ years, maker of fast sites.  I am interested in Web dev, but also giving time to other techs like Python, C, Rust, etc. I am currently 1st year student in IIITDM Kancheepuram, India. I love Cycling around for hours",
    url: "https://puruvj.dev/blog",
    twitter: "@puruvjdev",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "Node.js",
      "SCSS",
      "React",
      "StencilJS",
      "Svelte",
      "Angular",
    ],
  },
  {
    name: "Michael Asiedu",
    description:
      "A blog suited to  make you better and grow as software developer. Also, market and leverage your coding skills ",
    url: "https://blog.michaelasiedu.com",
    twitter: "@asiedu_dev",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Tailwind",
      "UI/UX Design",
      "Node.js",
      "Web3.0",
      "React",
      "Digital Marketing",
      "Personal Branding for developers",
      "APIs",
    ],
  },
  {
    name: "Devin Ford",
    description:
      "A blog for beginners, with tips and tricks I used while learning to code.",
    url: "https://blog.devinford.dev/",
    twitter: "@devinDford",
    tags: ["CSS", "Beginner", "Front End", "JavaScript"],
  },
  {
    name: "Oliver Jumpertz",
    description:
      "DeepDive covers cloud and web development overall. It tries to take a deeper look into how things work and explain them as simple as possible.",
    url: "https://deepdive.hashnode.dev/",
    twitter: "@oliverjumpertz",
    tags: [
      "JavaScript",
      "TypeScript",
      "AWS",
      "Rust",
      "Containers",
      "Kubernetes",
    ],
  },
  {
    name: "Daily Dev Tips",
    description:
      "Chris writes every single day about web development snippets that will help you become a better developer. He focuses on frontend development, JavaScript, popular frameworks, and HTML and CSS.",
    url: "https://daily-dev-tips.com/",
    twitter: "@DailyDevTips1",
    tags: ["HTML", "JavaScript", "CSS", "Beginner", "Web Development"],
  },
  {
    name: "Tshiteej Bhardwaj",
    description:
      "I love to write around Web Development, and related technologies.",
    url: "https://www.tshiteej.com/blog",
    twitter: "tshiteej",
    tags: ["JavaScript", "Python", "Web Development", "Automation"],
  },
  {
    name: "Victoria Lo",
    description:
      "Victoria is a very curious developer. Her articles on blogging combine great programming skills with enjoyable and insightful technical articles.",
    url: "https://lo-victoria.com",
    twitter: "@lo_victoria2666",
    tags: ["HTML", "CSS", "JavaScript", "Web Development", "React"],
  },
  {
    name: "Abiola Farounbi",
    description:
      "I am a Front-end Developer passionate about developing and designing user friendly web applications.i write technical contents and articles.",
    url: "https://abiolafarounbiblog.hashnode.dev/",
    twitter: "@abiolaesther_",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Front-end Development",
    ],
  },
  {
    name: "Aadhithyan Suresh",
    description: "Why you should switch to ubuntu today.",
    url: "https://aadhithyan.hashnode.dev/",
    twitter: "@Aadhithyan_17",
    tags: ["Linux", "Ubuntu", "Faster Development"],
  },
  {
    name: "Vlad Pasca",
    description:
      "Self-taught web developer, documenting my journey and sharing the projects I am working on",
    url: "https://vladpasca.hashnode.dev/",
    twitter: "@VladPasca5",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Beginner",
      "Self-taught",
    ],
  },
  {
    name: "Alba Silvente",
    description:
      "Front End developer and ambassador at Nuxt & Storyblok!. Blogging about Front End and working hard on the open-source to create more value for the web community. 🦸",
    url: "https://dawntraoz.com/blog/",
    twitter: "@dawntraoz",
    tags: [
      "Front End",
      "HTML",
      "JavaScript",
      "TailwindCSS",
      "Vue",
      "Nuxt",
      "Storyblok",
      "PWA",
      "Static Sites",
    ],
  },
  {
    name: "Christoph Werner",
    description:
      "Software architect writing about web development and cloud technology.",
    url: "https://codepunkt.de/writing/",
    twitter: "@code_punkt",
    tags: [
      "Web Development",
      "Software Architecture",
      "Cloud Infrastructure",
      "JavaScript",
      "Front End",
      "APIs",
      "GraphQL",
      "SaaS",
      "React",
      "Node.js",
    ],
  },
  {
    name: "Chris Kalmar",
    description:
      "Full stack developer, blogging about React, Nodejs, GraphQL, Docker, and personal experiences as a tech lead.",
    url: "https://chriskalmar.dev/blog/",
    twitter: "@chriskalmar",
    tags: [
      "Web Development",
      "JavaScript",
      "TypeScript",
      "React",
      "GraphQL",
      "Node.js",
      "Postgres",
      "Docker",
      "Kubernetes",
    ],
  },
  {
    name: "Kumusta Mundo",
    description:
      "Tech tutorials and stories from Adrienne Tacke, a Filipina software engineer.",
    url: "https://blog.adrienne.io/",
    twitter: "@adriennetacke",
    tags: [
      "Cloud",
      "Azure",
      "Software Engineering",
      "Cloud Infrastructure",
      "CSharp",
      "MongoDB",
      "NoSQL",
      "Women In Tech",
    ],
  },
  {
    name: "Juan Fernandes",
    description: "Freelance Web Designer",
    url: "https://www.juanfernandes.uk/blog",
    twitter: "@juanfernandes",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Web Design",
      "11ty",
      "SSG",
      "Front End",
      "TailwindCSS",
      "Web Hosting",
    ],
  },
  {
    name: "Code Create",
    description:
      "Exploring all things code and design. Diving into JavaScript, Python, and CS topics in 2021.",
    url: "https://blog.code-create.dev",
    twitter: "@kreyol_dev",
    tags: [
      "Web Development",
      "JavaScript",
      "Full Stack",
      "Python",
      "UX/UI",
      "Software Engineer",
      "Project Management",
      "Content Strategy",
      "Data Structures",
      "Algorithms",
    ],
  },
  {
    name: "ThisDot Blog",
    description:
      "Deep knowledge on web topics and tools. Written by many developers",
    url: "https://labs.thisdot.co/blog",
    twitter: "@ThisDotLabs",
    tags: [
      "Frontend",
      "JavaScript",
      "ReactJS",
      "VueJS",
      "Angular",
      "Web Development",
      "Tech",
      "GraphQL",
      "CSS",
      "AWS",
    ],
  },
  {
    name: "Albert Walicki",
    description: "Frontend developer, entrepreneur, writer, CSS artist",
    url: "https://www.albertwalicki.com/blog",
    twitter: "@AlbertWalicki",
    tags: [
      "CSS",
      "HTML",
      "JavaScript",
      "Next.js",
      "CSS art",
      "Accessibility",
      "Design",
      "SEO",
    ],
  },
  {
    name: "Varun Singh",
    description: "Full-stack Developer",
    url: "https://varuns.hashnode.dev",
    twitter: "varuns924",
    tags: [
      "JavaScript",
      "Web Development",
      "React",
      "Java",
      "Mobile App Development",
      "PHP",
      "Android",
      "MySQL",
      "SQL",
    ],
  },
  {
    name: "Rocco Sangellino",
    description:
      "I am a senior frontend developer with 10+ years of experience. I have experience building scalable, accessible, and responsive web applications using HTML, CSS, JavaScript, Vue.js and Node.js.",
    url: "https://blog.roccosangellino.com/",
    twitter: "@RoccoSangellino",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "TypeScript",
      "Node.js",
      "Vue",
      "Front End",
      "Bootstrap",
      "Git",
    ],
  },
  {
    name: "Corey O'Donnell",
    description:
      "Web developer, TypeScript Enthusiast. Blogging about web development and tech",
    url: "https://codebycorey.com/blog/",
    twitter: "@codebycorey",
    tags: [
      "Web Development",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Node.js",
    ],
  },
  {
    name: "Jason Ross",
    description:
      "👨🏻‍💻 Developer | ✍️ Blogger - I write about software engineering, algorithms and languages.",
    url: "https://www.softwarepragmatism.com/",
    tags: [
      "Python",
      "C#",
      "SQL",
      "C++",
      "Windows",
      "Linux",
      "Backend",
      "Fullstack",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "Stephan Kämper",
    description:
      "Programming & Software Test 〜 Languages: English, German, Ruby, and some Elixir",
    url: "https://seasidetesting.com/",
    twitter: "@S_2K",
    tags: [
      "Ruby",
      "Rails",
      "Software Test",
      "Testing",
      "Development",
      "HTML",
      "TDD",
      "BDD",
      "Git",
      "macOS",
    ],
  },
  {
    name: "Dan Spratling",
    description:
      "UX Consultant, making websites better for users for over 5 years",
    url: "https://danspratling.dev/blog/",
    twitter: "@dan_spratling",
    tags: [
      "Freelancing",
      "Career",
      "Finance",
      "User Experience",
      "Web Development",
      "Headless Development",
      "Design",
      "Accessibility",
      "Performance",
      "Productivity",
    ],
  },
  {
    name: "Umair Hafeez",
    description:
      "Front End Architect & Angular Fanatic 🅰️. I share whatever I have learned or learn during my day to day job. I believe in lean, share and grow philosophy, and that's the reason I started writing on this blog along with byte sized tips I share on Twitter and LinkedIn.",
    url: "https://blog.umairhafeez.com",
    twitter: "@_UmairHafeez_",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "Angular",
      "Web Development",
      "Accessibility",
    ],
  },
  {
    name: "Rishav Jadon",
    description:
      "This is my blog where I write all about css and the wonderful world of front end.",
    url: "https://csskenpai.com",
    twitter: "@rovenclasher",
    tags: ["Web Development", "JavaScript", "CSS", "HTML", "Front End"],
  },
  {
    name: "Harris Geo",
    description:
      "Software engineer blogging about full stack and career topics",
    url: "https://harrisgeo.me",
    twitter: "@harrisgeo88",
    tags: [
      "Web Development",
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Testing",
      "Career",
    ],
  },
  {
    name: "Scott Spence",
    description:
      "A detailed account of what Scott Spence is about. Currently learning TypeScript, Unit testing with React testing library with Jest and end to end testing with Cypress.",
    url: "https://scottspence.com",
    twitter: "@spences10",
    tags: [
      "TypeScript",
      "Jest",
      "Cypress",
      "CSS-inJS",
      "Static Sites",
      "Linux",
      "Ubuntu",
      "SEO",
      "GatsbyJS",
      "Front End",
    ],
  },
  {
    name: "Nilanth",
    description: "Full Stack Developer | Laravel | React",
    url: "https://nilanth.hashnode.dev",
    twitter: "@nilanth",
    tags: [
      "Front End",
      "React",
      "Redux",
      "Laravel",
      "PHP",
      "PostgreSQL",
      "Database",
      "Gatsby",
      "JavaScript",
      "AWS",
    ],
  },
  {
    name: "Florian Clanet",
    description:
      "Cloud entusiast who loves to build magical things in the Cloud. I am very curious and I try to share my new learnings with you.",
    url: "https://blog.flolight.dev/",
    twitter: "@FlolightC",
    tags: [
      "AWS",
      "Cloud",
      "Azure",
      "Beginner",
      "Devops",
      "Cloud Infrastructure",
      "Machine Learning",
      "Git",
      "General Programming",
      "Web Development",
    ],
  },
  {
    name: "WP OWls",
    description:
      "WP Owls is a place created especially for WordPress fans. Every week you will find the latest news from the world of WordPress.",
    url: "https://wpowls.co",
    twitter: "@WP_Owls",
    tags: ["WordPress", "Web Development"],
  },
  {
    name: "Idris Olubisi",
    description:
      "A Software Developer, Technical Writer and a Speaker skilled at problem-solving, technical leadership, communications, and presentations with vast experience in the full project life cycle from design to implementation to integration.",
    url: "https://blog.idrisolubisi.com/",
    twitter: "@olanetsoft",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Web Development",
      "Front End",
      "Backend",
      "Node.js",
      "TypeScript",
      "GraphQL",
    ],
  },
  {
    name: "Jeet Mandaliya",
    description:
      "I am a self-taught Frontend Developer with a thing for VIM. In my free time, you can find me tinkering with my terminal and trying out new oh-my-zsh themes.",
    url: "https://webdevjeet.me",
    twitter: "@sereneInSerenad",
    tags: [
      "JavaScript",
      "TypeScript",
      "Vue",
      "React",
      "Git",
      "GitHub",
      "VuetifyJS",
      "Node.js",
      "TailwindCSS",
      "Ghost CMS",
    ],
  },
  {
    name: "Stefan Natter",
    description:
      "I am a Software Engineer from Austria 🇦🇹. I am interested in, write about, and develop (open source) software solutions with JavaScript, TypeScript, ReactJS, and NodeJS.",
    url: "https://natterstefan.me",
    twitter: "@natterstefan",
    tags: [
      "Docker",
      "JavaScript",
      "Next.js",
      "Node.js",
      "Project Management",
      "React",
      "SEO",
      "TailwindCSS",
      "TypeScript",
      "Web Development",
    ],
  },
  {
    name: "Aman Mittal",
    description:
      "I am a fullstack developer and a technical writer. I am interested in React Native, React, Node.js and GraphQL. These are the topics that I often write about too.",
    url: "https://amanhimself.dev",
    twitter: "@amanhimself",
    tags: [
      "JavaScript",
      "Node.js",
      "React",
      "React Native",
      "Expo",
      "Front End",
      "GraphQL",
      "TypeScript",
      "Gatsby",
    ],
  },
  {
    name: "DeveloperAspire",
    description:
      "I am a Software engineer, writing about VueJs, JavaScript, Golang, Developers Tips and Hacks, Tailwind and open-source, Open-source contributor.",
    url: "https://developeraspire.hashnode.dev/",
    twitter: "@DeveloperAspire",
    tags: [
      "Golang",
      "TailwindCSS",
      "Vue",
      "Node.js",
      "Web Development",
      "Open source",
      "JavaScript",
    ],
  },
  {
    name: "Joshua Chinwendu",
    description:
      "Full Stack Developer. Love working with Python Django framework.",
    url: "https://joshualine.hashnode.dev",
    twitter: "@joshchinwendu",
    tags: [
      "JavaScript",
      "Python",
      "Node.js",
      "React",
      "Django",
      "APIs",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "Omomurewa George-Ashiru",
    description:
      "Murewa is a software developer and IT business analyst. She writes technical and career content.",
    url: "https://blog.murewaashiru.com/",
    twitter: "@rachael_xx",
    tags: [
      "JavaScript",
      "Web Development",
      "Node.js",
      "TypeScript",
      "Project Management",
      "Business Analysis",
    ],
  },
  {
    name: "Sushmita Pandey",
    description:
      "Frontend Developer 👩‍💻 | Tech Blogger ✍ | JavaScript Fanatic 🚀",
    url: "https://sushmita.hashnode.dev/",
    twitter: "@sushmitacodes",
    tags: [
      "JavaScript",
      "Web Development",
      "React",
      "CSS",
      "HTML",
      "Front End",
      "TypeScript",
      "TailwindCSS",
    ],
  },
  {
    name: "Rasmus Langvad",
    description:
      "Senior Frontend Developer from Sweden writing about web, tech and mentorship. Currently working with Vue, Nuxt and Node.",
    url: "https://langvad.dev/blog/",
    twitter: "@rlangvad",
    tags: [
      "JavaScript",
      "Front End",
      "Vue",
      "Nuxt",
      "Node.js",
      "TailwindCSS",
      "Web Development",
      "Storybook",
      "Design System",
      "Mentorship",
    ],
  },
  {
    name: "Austin Gil",
    description: "Writing about web development and life.",
    url: "https://austingil.com/blog/",
    twitter: "@Stegosource",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Vue",
      "Node.js",
      "Accessibility",
      "Security",
      "Serverless",
      "WordPress",
      "TypeScript",
    ],
  },
  {
    name: "Silvestar Bistrović",
    description: "Frontend, JAMstack, WordPress, and freelancing topics.",
    url: "https://develop.silvestar.codes/articles/",
    twitter: "@malimirkeccita",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Front End",
      "JAMstack",
      "WordPress",
      "Freelancing",
    ],
  },
  {
    name: "Matthew Hart",
    description:
      "DevOps focused developer, this is my blog where I discuss solutions I find while I work",
    url: "https://mattou07.net/",
    twitter: "@mattou07",
    tags: [
      "DevOps",
      "Web Development",
      "C#",
      "Azure",
      "Umbraco",
      "Powershell",
      "IIS",
    ],
  },
  {
    name: "Ankur Tyagi",
    description:
      "Hi, I’m Ankur Tyagi, Software Engineer, Mentor, Coach, Content creator, Checkout my website for more details at https://theankurtyagi.com/",
    url: "https://theankurtyagi.com/blog/",
    twitter: "@TheAnkurTyagi",
    tags: [
      "Web Development",
      "JavaScript",
      "Python",
      "HTML",
      "React",
      "Freelancing",
      "Mentorship",
      "WordPress",
      "Software Development",
      "Software Architecture",
      "Software Engineering",
      "Software Engineer",
      "Project Management",
      "Front End",
      "CSS",
    ],
  },
  {
    name: "Mads Brodt",
    description:
      "Front-end engineer. Sharing technical tutorials and career advice to help you become a better developer.",
    url: "https://madsbrodt.com/blog/",
    twitter: "@madsbrodt",
    tags: [
      "JavaScript",
      "Web Development",
      "HTML",
      "CSS",
      "TailwindCSS",
      "React",
      "Vue",
      "Front End",
      "Freelancing",
      "Career",
    ],
  },
  {
    name: "James Drysdale",
    description:
      "Frontend Developer from Scotland writing about web development. Currently working with React, React Native and Node.",
    url: "https://jamesdrysdale.hashnode.dev/",
    twitter: "@JamesDrysdale84",
    tags: [
      "JavaScript",
      "HTML",
      "CSS",
      "Front End",
      "Web Development",
      "React",
      "React Native",
      "SEO",
    ],
  },
  {
    name: "Piyush Sinha",
    description: "Frontend Engineer | Problem Solver",
    url: "https://piyushsinha.tech/",
    twitter: "@devps2020",
    tags: [
      "JavaScript",
      "Web Development",
      "React",
      "Web Components",
      "Chrome Extension",
    ],
  },
  {
    name: "Victor Meunier",
    description: "Software engineer | Gamedev",
    url: "https://blog.victormeunier.com/",
    twitter: "@VicMeunier",
    tags: ["Web", "CV", "ML", "DL", "Gamedev"],
  },
  {
    name: "Unicorn Utterances",
    description: "Learning programming from magically majestic words.",
    url: "https://unicorn-utterances.com/",
    twitter: "@UnicornUttrncs",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "React",
      "Angular",
      "Front End",
      "Node.js",
      "Programming",
      "General Tech",
    ],
  },
  {
    name: "Saad Ahmad",
    description: "Frontend developer | Mechanical engineer",
    url: "https://medium.com/@saadahmadhere",
    twitter: "@imsaadahmad",
    tags: ["Github", "API", "Mongoose", "Express", "Node.js", "Hyper terminal"],
  },
  {
    name: "Tim Robards",
    description:
      "Frontend Developer and creator of easeout.co, a blog/community for web developers and designers alike!",
    url: "https://easeout.co",
    twitter: "@easeoutco",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Web Development",
      "Angular",
      "React",
      "Node.js",
      "Front End",
    ],
  },
  {
    name: "Peter Smulovics",
    description: "Dad, Geek, Geek Dad - Microsoft enthusiast",
    url: "https://dotneteers.net",
    twitter: "@mountgellert",
    tags: [
      "Microsoft",
      ".NET",
      "C#",
      "Software Development",
      "Software Architecture",
      "Software Engineering",
      "Software Engineer",
      "Project Management",
      "Mentorship",
    ],
  },
  {
    name: "Learnedia",
    description: "WP dev tips and tricks, conversion tracking tips",
    url: "https://learnedia.com/",
    twitter: "@helloImLearnrr",
    tags: [
      "WordPress",
      "PHP",
      "HTML",
      "CSS",
      "JavaScript",
      "Conversion tracking",
      "GTM",
      "GA",
      "SEO",
    ],
  },
  {
    name: "Dillion Megida",
    description:
      "Software Engineer and Content creator passionate about simplifying topics around web development",
    url: "https://dillionmegida.com/blog",
    twitter: "@iamdillion",
    tags: [
      "Frontend",
      "JavaScript",
      "ReactJS",
      "NextJS",
      "GatsbyJS",
      "Web Development",
      "Tech",
      "Node.JS",
      "CSS",
      "TypeScript",
    ],
  },
  {
    name: "Steven Spads",
    description:
      "Full-stack Web Developer from Canada. Sharing web development tips, techniques, and tutorials to help you become a better web developer.",
    url: "https://lumin8media.com",
    twitter: "@stevenspads",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "Angular",
      "React",
      "Node.js",
      "NestJS",
      "Laravel",
      "Web Development",
    ],
  },
  {
    name: "Emmanuel Ezeka",
    description:
      "A frontend web developer, Electrical/Electronics Engineer, Passionate about problem-solving.",
    url: "https://eecvision.hashnode.dev/",
    twitter: "@EECvision",
    tags: [
      "HTML",
      "CSS",
      "Tailwindcss",
      "JavaScript",
      "React",
      "Node.js",
      "Git",
      "Web Development",
    ],
  },
  {
    name: "Rishab Kumar",
    description:
      "I am a tech entusiast that loves to play in the Cloud and related technologies. Also, try to create nice web experiences.",
    url: "https://blog.rishabkumar.com/",
    twitter: "@rishabk7",
    tags: [
      "AWS",
      "Cloud",
      "Azure",
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Git",
      "General Programming",
      "Web Development",
    ],
  },
  {
    name: "Sebastian Hesse",
    description:
      "Serverless Cloud Expert - Blogging about everything related to AWS Cloud, Serverless, Java, Node.js and JavaScript.",
    url: "https://www.sebastianhesse.de/blog",
    twitter: "@seeebiii",
    tags: [
      "Software Engineer",
      "AWS",
      "Serverless",
      "Cloud Infrastructure",
      "APIs",
      "Java",
      "JavaScript",
      "TypeScript",
      "Node.js",
      "Web Development",
    ],
  },
  {
    name: "Marcel Hauri",
    description:
      "Father, husband, software developer and lecturer in application development.",
    url: "https://marcelhauri.ch/blog/",
    twitter: "@mhauri",
    tags: [
      "DevOps",
      "Docker",
      "Netlify",
      "Google Cloud Platform",
      "Laravel",
      "Symfony",
      "React",
      "Next",
      "Gatsby",
      "Tailwind CSS",
    ],
  },
  {
    name: "Chen A",
    description:
      "Just another blog about Devops/SRE - blog about infrastructure, software-engineering, et al.",
    url: "https://devopsian.net",
    tags: [
      "Software Engineer",
      "AWS",
      "Cloud",
      "Infrastructure",
      "Git",
      "Python",
      "Productivity",
      "Docker",
      "Linux",
      "Kubernetes",
    ],
  },
  {
    name: "Godswill Umukoro",
    description: "Software engineer who loves building frontend applications",
    url: "https://godswillumukoro.hashnode.dev",
    twitter: "@umuks_",
    tags: [
      "Software Engineer",
      "Javascript",
      "React",
      "Node.js",
      "APIs",
      "Web Development",
    ],
  },
  {
    name: "Sebastian Urban",
    description: ".NET Developer, Tech Lover",
    url: "https://sebastianurban.dev/blog",
    twitter: "@seburbandev",
    tags: [
      "Software Developer",
      "C#",
      ".NET",
      "Csharp",
      "APIs",
      "Web Development",
      "Tech",
      "Productivity",
      "Umbraco",
    ],
  },
  {
    name: "@litbelb on Medium",
    description: "Gopher, Student, Gamer, very unprofessional writer",
    url: "https://medium.litbelb.com",
    twitter: "@Litbelb",
    tags: ["Golang", "Front End", "Web Development", "Vue"],
  },
  {
    name: "Jai Kumar Dewani",
    description: "Another Tech-nerd trying to make a name for himself.",
    url: "https://jai-dewani.github.io/blogs/",
    twitter: "@jai_dewani",
    tags: [
      "Software Developer",
      "Python",
      "JavaScript",
      "Node.js",
      "React",
      "Algorithms",
      "SEO",
      "APIs",
      "Web Development",
      "Tech",
    ],
  },
  {
    name: "Peter Lynch",
    description:
      "Full-stack developer and creator of popular chrome extension Garachu. I write about web development and help you level up your coding.",
    url: "https://peterlunch.com/articles/",
    twitter: "@thelynchpinau",
    tags: ["HTML", "CSS", "JavaScript", "Web Development", "Beginner", "React"],
  },
  {
    name: "Sakun Pushpitha",
    description:
      "Web development resources, tutorials, tips and tricks for developers.",
    url: "https://sakunpushpitha.hashnode.dev",
    twitter: "@SakunPushpitha",
    tags: [
      "Web Development",
      "Backend",
      "Git",
      "Front End",
      "React",
      "Javascript",
      "APIs",
      "Node.js",
      "CSS",
      "HTML",
    ],
  },
  {
    name: "Sarah Drasner",
    description:
      "The author of SVG Animations from O’Reilly and a staff writer for CSS-Tricks.",
    url: "https://sarah.dev/writing",
    twitter: "@sarah_edo",
    tags: [
      "SVG",
      "Vue",
      "JavaScript",
      "Self-Development",
      "Tech",
      "Web Development",
    ],
  },
  {
    name: "Sven Hofmann",
    description: "Thoughts, resources, and hacks for developers.",
    url: "https://hofmannsven.com/blog",
    twitter: "@hofmannsven",
    tags: [
      "APIs",
      "Backend",
      "Git",
      "Laravel",
      "PHP",
      "Self-Development",
      "Tech",
      "Web Development",
    ],
  },
  {
    name: "Filipe Oliveira",
    description:
      "codeperf.io: Blog empowering developers with tools and how-to to make software faster.",
    url: "https://codeperf.io",
    twitter: "@fcosta_oliveira",
    tags: [
      "Performance",
      "Observability",
      "Monitoring",
      "C",
      "Golang",
      "NOSQL",
      "Redis",
    ],
  },
  {
    name: "Ravgeet Dhillon",
    description: "Full Stack Developer and Technical Content Writer",
    url: "https://www.ravgeet.in/blog/",
    twitter: "@ravgeetdhillon",
    tags: [
      "React",
      "Vue",
      "Flutter",
      "Laravel",
      "Python",
      "Integration",
      "API",
      "Strapi",
      "Node",
      "Automation",
      "Google Apps Script",
      "Javascript",
      "Frontend",
      "Fullstack",
      "Freelancing",
      "Career",
      "Software Development",
    ],
  },
  {
    name: "Bisrategebriel Fisseha",
    description:
      "Software Engineer| Graphic Designer | Tech Entrepreneur | Cofounder at Kuraztech",
    url: "https://bisrate22.medium.com/",
    twitter: "@Bisrate22Fish",
    tags: [
      "Tech",
      "Software Development",
      "Freelancing",
      "Career",
      "Git",
      "JavaScript",
      "Frontend",
      "Gaming",
      "Blender",
      "Unreal",
    ],
  },
  {
    name: "Hassan Sani",
    description: "Writing about frontend and Angular.",
    url: "https://blog.hassansani.me",
    twitter: "@inidaname",
    tags: [
      "APIs",
      "Front End",
      "Git",
      "Angular",
      "Self-Development",
      "Tech",
      "Web Development",
    ],
  },
  {
    name: "Preston Lamb",
    description: "Full Stack developer, focusing on Angular and Node",
    url: "https://www.prestonlamb.com/blog",
    twitter: "prestonjlamb",
    tags: ["Angular", "JavaScript", "Node.js", "Nest.js", "Web Development"],
  },
  {
    name: "Priya Pareek",
    description: "Used to write about TechSavvy",
    url: "https://techsavvypriya.wordpress.com/",
    twitter: "iampriyapareek",
    tags: [
      "Front End",
      "Git",
      "Angular",
      "Self-Development",
      "Tech",
      "Web Development",
      "Progrmaming",
      "Artificial Intelligence",
      "Cheat Sheets",
      "Technical",
    ],
  },
  {
    name: "Vishunbhotla V D V Bharadwaj",
    description:
      "A Computer Science Engineer who loves Blogging and Sharing Content",
    url: "https://bharadwaj.hashnode.dev/",
    twitter: "@Bharadwaj6262",
    tags: ["Python", "Flutter", "Web Development", "Computer Science"],
  },
  {
    name: "Alex Lakatos",
    description:
      "Reformed JavaScript person. Tech Lead by day, Developer Avocado 🥑 by night.",
    url: "https://alexlakatos.com/",
    twitter: "@lakatos88",
    tags: ["JavaScript", "DevTools", "DevRel"],
  },
  {
    name: "Shahed Nasser",
    description:
      "Writing about anything related to Web Development or Personal Opinions.",
    url: "https://blog.shahednasser.com/",
    twitter: "@shahednasserr",
    tags: [
      "Front End",
      "Javascript",
      "Web Development",
      "Git",
      "Technical",
      "Tech",
      "Programming",
      "React",
      "PHP",
      "CSS",
      "Node.js",
      "Magento",
      "Computer Science",
    ],
  },
  {
    name: "Adithya",
    description:
      "I write about solutions to problems that I face on a daily basis | PHP, Laravel developer in Berlin, Germany",
    url: "https://adithya.dev/",
    twitter: "@adithya_srini",
    tags: [
      "PHP",
      "Laravel",
      "Backend",
      "Full Stack",
      "Elasticsearch",
      "Tailwind",
    ],
  },
  {
    name: "Kolawole Mangabo",
    description:
      "I write about JavaScript and Python | React, Django developer ",
    url: "https://koladev.xyz/blog/",
    twitter: "@koladev32",
    tags: [
      "JavaScript",
      "TypeScript",
      "Python",
      "Django",
      "React",
      "Docker",
      "Tailwind",
    ],
  },
  {
    name: "Bogdan Alexandru Militaru",
    description:
      "I write about programming, devops and my startup journey. | Software Engineer",
    url: "https://boobo94.github.io/",
    twitter: "@militaru_bogdan",
    tags: [
      "programming",
      "APIs",
      "backend",
      "frontend",
      "JavaScript",
      "Nodejs",
      "Vuejs",
      "devops",
    ],
  },
];
