module.exports = [
  {
    name: 'Marko Denic',
    description: 'Web developer. Helping others become one too.',
    url: 'https://markodenic.com/blog/',
    twitter: '@denicmarko',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
    ],
  },
  {
    name: 'Danny Steenman',
    description: 'I’m an AWS Cloud Consultant who likes to build things in the Cloud. I write about my learnings on this Blog and on Twitter.',
    url: 'https://dannys.cloud/',
    twitter: '@dannysteenman',
    tags: [
      'AWS',
      'Certification',
      'Cloud',
      'Infrastructure',
      'Python',
    ],
  },
  {
    name: 'Savio Martin',
    description: 'A 13-year-old boy on an intention to enhance as a successful full-stack web developer. I love building full-stack web applications and mobile apps.',
    url: 'https://savio.xyz/',
    twitter: '@saviomartin7',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'Frontend',
      'Node.js',
      'App Development',
      'React',
      'React Native',
      'UI/UX',
    ],
  },
  {
    name: 'Nat Miletic',
    description: '',
    url: 'https://cliowebsites.com/blog/',
    twitter: '@natmiletic',
    tags: [
      'Web Design',
      'WordPress',
      'SEO',
    ],
  },
  {
    name: 'Devin Ford',
    description: 'A blog for beginners, with tips and tricks I used while learning to code.',
    url: 'https://blog.devinford.dev/',
    twitter: '@devinDford',
    tags: [
      'CSS',
      'Beginner',
      'Front End',
      'JavaScript',
    ],
  },
  {
    name: 'Oliver Jumpertz',
    description: 'DeepDive covers cloud and web development overall. It tries to take a deeper look into how things work and explain them as simple as possible.',
    url: 'https://deepdive.hashnode.dev/',
    twitter: '@oliverjumpertz',
    tags: [
      'JavaScript',
      'TypeScript',
      'AWS',
      'Rust',
      'Containers',
      'Kubernetes',
    ],
  },
  {
    name: 'Daily Dev Tips',
    description: 'Chris writes every single day about web development snippets that will help you become a better developer. He focuses on frontend development, JavaScript, popular frameworks, and HTML and CSS.',
    url: 'https://daily-dev-tips.com/',
    twitter: '@DailyDevTips1',
    tags: [
      'HTML',
      'JavaScript',
      'CSS',
      'Beginner',
      'Web Development'
    ],
  },
  {
    name: 'Aadhithyan Suresh',
    description: 'Why you should switch to ubuntu today.',
    url: 'https://aadhithyan.hashnode.dev/',
    twitter: '@Aadhithyan_17',
    tags: [
      'Linux',
      'Ubuntu',
      'Faster Development',
    ],
  },
  {
    name: 'Vlad Pasca',
    description: 'Self-taught web developer, documenting my journey and sharing the projects I am working on',
    url: 'https://vladpasca.hashnode.dev/',
    twitter: '@VladPasca5',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'Beginner',
      'Self-taught',
    ],
  },
  {
    name: 'Corey O\'Donnell',
    description: 'Web developer, TypeScript Enthusiast. Blogging about web development and tech',
    url: 'https://codebycorey.com/blog/',
    twitter: '@codebycorey',
    tags: [
      'Web Development',
      'JavaScript',
      'TypeScript',
      'React',
      'Next.js',
      'Node.js'
    ],
  }
];
