module.exports = [
  {
    name: 'Marko ⚡ Denic',
    description: 'Web developer. IT consultant and trainer.',
    url: 'https://markodenic.com/blog/',
    twitter: '@denicmarko',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'Vue',
      'Nuxt',
      'Front End',
      'Laravel',
      'TailwindCSS',
      'SEO',
    ],
  },
  {
    name: 'Tosin Fashanu',
    description: 'Portfolio | Tutorial | Agency for web development.',
    url: 'https://apluswebmaker.com',
    twitter: '@iamJohnFashanu',
    tags: [
      'JavaScript',
      'PHP',
      'React',
      'laravel',
      'Web Development',
      'HTML',
      'CSS'
    ],
  },
  {
    name: 'Olena Drugalya',
    description: 'Olena is self-taught web developer and she writes her beginner-friendly and simply explained tech blogs along the way.',
    url: 'https://olena.hashnode.dev/',
    twitter: '@OlenaDrugalya',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'React'
    ],
  },
  {
    name: 'Abia Tech Hub',
    description: 'Innovation | Technoloy | Entrepreneurship',
    url: 'https://blog.abiatechhub.com',
    twitter: '@abiatechhub',
    tags:[
      'JavaScript',
      'Web Development',
      'React',
      'Web Components',
      'Chrome Extension',
      'Freelancing',
      'Mentorship',
      'WordPress',
      'Software Development',
      'Software Architecture',
    ]
  },
  {
    name: 'Abdulmalik Adekunle',
    description: 'Front End Web developer, Graphics Designer, IT consultant.',
    url: 'https://abdulmalik.hashnode.dev',
    twitter: '@Emeritus_Ade',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'React',
      'Next.js',
      'Front End',
      'Node.js',
      'Bootstrap',
      'General Tech',
    ],
  },
  {
    name: 'impure.fun',
    description: 'Functional code for humans',
    url: 'https://impure.fun',
    twitter: '@luwvis',
    tags: [
      'DDD',
      'F#',
      'Functional',
      '.NET',
    ],
  },
  {
    name: 'dubesar',
    description: 'Python/JS Developer',
    url: 'https://dubesar.hashnode.dev',
    twitter: '@Sarvesh12601156',
    tags: [
      'JavaScript',
      'Python',
      'C++',
      'Node',
      'Deep Learning',
      'Flask',
      'API',
      'UI Developer',
      'HTML',
      'CSS',
      'TailwindCSS',
    ],
  },
  {
    name: 'Rahul',
    description: 'Front-end Developer. Helping beginners in coding.',
    url: 'https://blog.rahulism.co',
    twitter: '@rahxul',
    tags: [
      'HTML',
      'CSS',
      'React',
      'Beginners',
      'Web Development',
      'JavaScript',
      'Front End',
      'Productivity',
    ],
  },
  {
    name: 'Sunil Sandhu',
    description: 'Software Developer, Founder of In Plain English',
    url: 'https://sunilsandhu.com/',
    twitter: '@sunilsandhu',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'Vue',
      'React',
      'Front End',
      'Computer Science',
      'Algorithms',
      'Python',
    ],
  },
  {
    name: 'Danny Steenman',
    description: 'I’m an AWS Cloud Consultant who likes to build things in the Cloud. I write about my learnings on this Blog and on Twitter.',
    url: 'https://dannys.cloud/',
    twitter: '@dannysteenman',
    tags: [
      'AWS',
      'Certification',
      'Cloud',
      'Infrastructure',
      'Python',
    ],
  },
  {
    name: 'Jiri Tichy',
    description: 'I’m helping companies fight technical debt and deliver better software faster. Our automated tool Codeac.io covers our back as well.',
    url: 'https://www.codeac.io/blog/',
    twitter: '@tichy_jiri',
    tags:[
      'Clean Code',
      'Technical Debt',
      'Code Quality',
      'Infrastrucutre as Code',
      'Infrastructure',
      'Cloud Infrastructure',
      'Productivity',
      'Faster Development',
    ]
  },
  {
    name: 'Sam Larsen-Disney',
    description: 'Sam currently works as a UX Engineer at American Express. He has built new ways to refer friends, onboarding experiences and rapid response systems.',
    url: 'https://sld.codes/articles',
    twitter: '@SamLarsenDisney',
    tags:[
      'JavaScript',
      'Gatsby',
      'SCSS',
      'Front End',
      'Web Development',
      'React',
      'TailwindCSS',
      'UX Design',
    ]
  },
  {
    name: 'Bhanu Teja Pachipulusu',
    description: 'Full-Stack Developer, Entrepreneur and Co-Founder of Coderplex. Building https://coderplex.in. Checkout my portfolio at https://bhanuteja.dev',
    url: 'https://blog.bhanuteja.dev',
    twitter: '@pbteja1998',
    tags: [
      'Web Development',
      'JavaScript',
      'TypeScript',
      'React',
      'Next.js',
      'GraphQL',
      'TailwindCSS',
      'Front End',
      'HTML',
      'CSS',
    ],
  },
  {
    name: 'Savio Martin',
    description: 'A 13-year-old boy on an intention to enhance as a successful full-stack web developer. I love building full-stack web applications and mobile apps.',
    url: 'https://savio.xyz/',
    twitter: '@saviomartin7',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'Front End',
      'Node.js',
      'App Development',
      'React',
      'React Native',
      'UI/UX',
    ],
  },
  {
    name: 'Sunil Kumar',
    description: 'I write about how to become a better developer, AWS, freelancing & building SaaS products.',
    url: 'https://sunilkumarc.in',
    twitter: '@sunilc_',
    tags: [
      'Web Development',
      'Freelancing',
      'Python',
      'Software Design',
      'Software Architecture',
      'AWS',
      'Infrastructure'
    ],
  },
  {
    name: 'Alexander Rowsell',
    description: 'Hardware hacker/embedded dev',
    url: 'https://frozenelectronics.ca/',
    twitter: '@FrozenElecBlog',
    tags:[
      'Embedded',
      'Hardware hacker',
      'Canadian hacker',
      'C',
      'Assembly language',
    ]
  },
  {
    name: 'Nat Miletic',
    description: 'This blog covers a range of topics related to responsive web design, web development, and WordPress how-to guides.',
    url: 'https://cliowebsites.com/blog/',
    twitter: '@natmiletic',
    tags: [
      'Web Design',
      'WordPress',
      'SEO',
    ],
  },
  {
    name: 'Alexander Lichter',
    description: 'Nuxt.js maintainer and Web Development Consultant. I love to blog about various technical topics with a focus on web development, especially with Vue and Nuxt.',
    url: 'https://blog.lichter.io/?ref=tech-blogs.dev',
    twitter: '@TheAlexLichter',
    tags: [
      'Nuxt',
      'Vue',
      'TailwindCSS',
      'JavaScript',
      'Web Development',
      'SEO',
      'Clean Code',
      'SSR',
      'Jamstack',
      'Refactoring'
    ],
  },
  {
    name: 'Ramya Chinnadurai (Rams)',
    description: 'Full stack web developer. Passionate programmer and curious learner. Building http://100daysof.codes ',
    url: 'http://rams.codes/',
    twitter: '@code_rams',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'React',
      'Node.js',
      'Chrome extensions',
      'Next.js'
    ],
  },
  {
    name: 'Puru Vijay',
    description: 'Fullstack Developer 6+ years, maker of fast sites.  I am interested in Web dev, but also giving time to other techs like Python, C, Rust, etc. I am currently 1st year student in IIITDM Kancheepuram, India. I love Cycling around for hours' ,
    url: 'https://puruvj.dev/blog' ,
    twitter: '@puruvjdev' ,
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'TypeScript',
      'Node.js',
      'SCSS',
      'React',
      'StencilJS',
      'Svelte',
      'Angular',
    ]
  },
  {
    name: 'Devin Ford',
    description: 'A blog for beginners, with tips and tricks I used while learning to code.',
    url: 'https://blog.devinford.dev/',
    twitter: '@devinDford',
    tags: [
      'CSS',
      'Beginner',
      'Front End',
      'JavaScript',
    ],
  },
  {
    name: 'Oliver Jumpertz',
    description: 'DeepDive covers cloud and web development overall. It tries to take a deeper look into how things work and explain them as simple as possible.',
    url: 'https://deepdive.hashnode.dev/',
    twitter: '@oliverjumpertz',
    tags: [
      'JavaScript',
      'TypeScript',
      'AWS',
      'Rust',
      'Containers',
      'Kubernetes',
    ],
  },
  {
    name: 'Daily Dev Tips',
    description: 'Chris writes every single day about web development snippets that will help you become a better developer. He focuses on frontend development, JavaScript, popular frameworks, and HTML and CSS.',
    url: 'https://daily-dev-tips.com/',
    twitter: '@DailyDevTips1',
    tags: [
      'HTML',
      'JavaScript',
      'CSS',
      'Beginner',
      'Web Development'
    ],
  },
  {
    name: 'Victoria Lo',
    description: 'Victoria is a very curious developer. Her articles on blogging combine great programming skills with enjoyable and insightful technical articles.',
    url: 'https://lo-victoria.com',
    twitter: '@lo_victoria2666',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'React'
    ],
  },
    {
    name: 'Abiola Farounbi',
    description: 'I am a Front-end Developer passionate about developing and designing user friendly web applications.i write technical contents and articles.',
    url: 'https://abiolafarounbiblog.hashnode.dev/',
    twitter: '@abiolaesther_',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'Front-end Development'
    ],
  },
  {
    name: 'Aadhithyan Suresh',
    description: 'Why you should switch to ubuntu today.',
    url: 'https://aadhithyan.hashnode.dev/',
    twitter: '@Aadhithyan_17',
    tags: [
      'Linux',
      'Ubuntu',
      'Faster Development',
    ],
  },
  {
    name: 'Vlad Pasca',
    description: 'Self-taught web developer, documenting my journey and sharing the projects I am working on',
    url: 'https://vladpasca.hashnode.dev/',
    twitter: '@VladPasca5',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'Beginner',
      'Self-taught',
    ],
  },
  {
    name: 'Alba Silvente',
    description: 'Front End developer and ambassador at Nuxt & Storyblok!. Blogging about Front End and working hard on the open-source to create more value for the web community. 🦸',
    url: 'https://dawntraoz.com/blog/',
    twitter: '@dawntraoz',
    tags: [
      'Front End',
      'HTML',
      'JavaScript',
      'TailwindCSS',
      'Vue',
      'Nuxt',
      'Storyblok',
      'PWA',
      'Static Sites'
    ],
  },
  {
    name: 'Christoph Werner',
    description: 'Software architect writing about web development and cloud technology.',
    url: 'https://codepunkt.de/writing/',
    twitter: '@code_punkt',
    tags: [
      'Web Development',
      'Software Architecture',
      'Cloud Infrastructure',
      'JavaScript',
      'Front End',
      'APIs',
      'GraphQL',
      'SaaS',
      'React',
      'Node.js'
    ],
  },
  {
    name: 'Chris Kalmar',
    description: 'Full stack developer, blogging about React, Nodejs, GraphQL, Docker, and personal experiences as a tech lead.',
    url: 'https://chriskalmar.dev/blog/',
    twitter: '@chriskalmar',
    tags: [
      'Web Development',
      'JavaScript',
      'TypeScript',
      'React',
      'GraphQL',
      'Node.js',
      'Postgres',
      'Docker',
      'Kubernetes'
    ],
  },
  {
    name: 'Kumusta Mundo',
    description: 'Tech tutorials and stories from Adrienne Tacke, a Filipina software engineer.',
    url: 'https://blog.adrienne.io/',
    twitter: '@adriennetacke',
    tags: [
      'Cloud',
      'Azure',
      'Software Engineering',
      'Cloud Infrastructure',
      'CSharp',
      'MongoDB',
      'NoSQL',
      'Women In Tech'
    ],
  },
  {
    name: 'Code Create',
    description: 'Exploring all things code and design. Diving into JavaScript, Python, and CS topics in 2021.',
    url: 'https://blog.code-create.dev',
    twitter: '@kreyol_dev',
    tags: [
      'Web Development',
      'JavaScript',
      'Full Stack',
      'Python',
      'UX/UI',
      'Software Engineer',
      'Project Management',
      'Content Strategy',
      'Data Strutures',
      'Algorithms'
    ],
  },
    {
    name: 'Varun Singh',
    description: 'Full-stack Developer',
    url: 'https://varuns.hashnode.dev',
    twitter: 'varuns924',
    tags: [
      'JavaScript',
      'Web Development',
      'React',
      'Java',
      'Mobile App Development',
      'PHP',
      'Android',
      'MySQL',
      'SQL'
    ]
	},
  {
    name: 'Rocco Sangellino',
    description: 'I am a senior frontend developer with 10+ years of experience. I have experience building scalable, accessible, and responsive web applications using HTML, CSS, JavaScript, Vue.js and Node.js.',
    url: 'https://blog.roccosangellino.com/',
    twitter: '@RoccoSangellino',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',
      'TypeScript',
      'Node.js',
      'Vue',
      'Front End',
      'Bootstrap',
      'Git',
    ],
  },
  {
    name: 'Corey O\'Donnell',
    description: 'Web developer, TypeScript Enthusiast. Blogging about web development and tech',
    url: 'https://codebycorey.com/blog/',
    twitter: '@codebycorey',
    tags: [
      'Web Development',
      'JavaScript',
      'TypeScript',
      'React',
      'Next.js',
      'Node.js'
    ],
  },
  {
    name: 'Dan Spratling',
    description: 'UX Consultant, making websites better for users for over 5 years',
    url: 'https://danspratling.dev/blog/',
    twitter: '@dan_spratling',
    tags: [
      'Freelancing',
      'Career',
      'Finance',
      'User Experience',
      'Web Development',
      'Headless Development',
      'Design',
      'Accessibility',
      'Performance',
      'Productivity',
    ],
  },
  {
    name: 'Umair Hafeez',
    description: 'Front End Architect & Angular Fanatic 🅰️. I share whatever I have learned or learn during my day to day job. I believe in lean, share and grow philosophy, and that\'s the reason I started writing on this blog along with byte sized tips I share on Twitter and LinkedIn.',
    url: 'https://blog.umairhafeez.com',
    twitter: '@_UmairHafeez_',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'TypeScript',
      'Angular',
      'Web Development',
      'Accessibility'
    ]
  },
  {
    name: 'Rishav Jadon',
    description: 'This is my blog where I write all about css and the wonderful world of front end.',
    url: 'https://csskenpai.com',
    twitter: '@rovenclasher',
    tags: [
      'Web Development',
      'JavaScript',
      'CSS',
      'HTML',
      'Front End'
    ],
  },
  {
    name: 'Harris Geo',
    description: 'Software engineer blogging about full stack and career topics',
    url: 'https://harrisgeo.me',
    twitter: '@harrisgeo88',
    tags: [
      'Web Development',
      'JavaScript',
      'TypeScript',
      'React',
      'Node.js',
      'Testing',
      'Career'
    ],
  },
  {
    name: 'Scott Spence',
    description: 'A detailed account of what Scott Spence is about. Currently learning TypeScript, Unit testing with React testing library with Jest and end to end testing with Cypress.',
    url: 'https://scottspence.com',
    twitter: '@spences10',
    tags: [
      'TypeScript',
      'Jest',
      'Cypress',
      'CSS-inJS',
      'Static Sites',
      'Linux',
      'Ubuntu',
      'SEO',
      'GatsbyJS',
      'Front End'
    ],
  },
  {
    name: 'Nilanth',
    description: 'Full Stack Developer | Laravel | React',
    url: 'https://nilanth.hashnode.dev',
    twitter: '@nilanth',
    tags: [
      'Front End',
      'React',
      'Redux',
      'Laravel',
      'PHP',
      'PostgreSQL',
      'Database',
      'Gatsby',
      'JavaScript',
      'AWS',
    ],
  },
  {
    name: 'WP OWls',
    description: 'WP Owls is a place created especially for WordPress fans. Every week you will find the latest news from the world of WordPress.',
    url: 'https://wpowls.co',
    twitter: '@WP_Owls',
    tags: [
      'WordPress',
      'Web Development',
    ]
  },
  {
    name: 'Idris Olubisi',
    description: 'A Software Developer, Technical Writer and a Speaker skilled at problem-solving, technical leadership, communications, and presentations with vast experience in the full project life cycle from design to implementation to integration.',
    url: 'https://blog.idrisolubisi.com/',
    twitter: '@olanetsoft',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Web Development',
      'Front End',
      'Backend',
      'Node.js',
      'TypeScript',
      'GraphQL'
    ],
  },
  {
    name: 'Jeet Mandaliya',
    description: 'I am a self-taught Frontend Developer with a thing for VIM. In my free time, you can find me tinkering with my terminal and trying out new oh-my-zsh themes.',
    url: 'https://webdevjeet.me',
    twitter: '@sereneInSerenad',
    tags: [
      'JavaScript',
      'TypeScript',
      'Vue',
      'React',
      'Git',
      'GitHub',
      'VuetifyJS',
      'Node.js',
      'TailwindCSS',
      'Ghost CMS'
    ]
  },
  {
    name: 'Stefan Natter',
    description: 'I am a Software Engineer from Austria 🇦🇹. I am interested in, write about, and develop (open source) software solutions with JavaScript, TypeScript, ReactJS, and NodeJS.',
    url: 'https://natterstefan.me',
    twitter: '@natterstefan',
    tags: [
      'Docker',
      'JavaScript',
      'Next.js',
      'Node.js',
      'Project Management',
      'React',
      'SEO',
      'TailwindCSS',
      'TypeScript',
      'Web Development',
    ]
  },
  {
    name: 'Aman Mittal',
    description: 'I am a fullstack developer and a technical writer. I am interested in React Native, React, Node.js and GraphQL. These are the topics that I often write about too.',
    url: 'https://amanhimself.dev',
    twitter: '@amanhimself',
    tags: [
      'JavaScript',
      'Node.js',
      'React',
      'React Native',
      'Expo',
      'Front End',
      'GraphQL',
      'TypeScript',
      'Gatsby'
    ]
  },
  {
    name:'DeveloperAspire',
    description: 'I am a Software engineer, writing about VueJs, JavaScript, Golang, Developers Tips and Hacks, Tailwind and open-source, Open-source contributor.',
    url: 'https://developeraspire.hashnode.dev/',
    twitter: '@DeveloperAspire',
    tags:[
      'Golang',
      'TailwindCSS',
      'Vue',
      'Node.js',
      'Web Development',
      'Open source',
      'JavaScript',
    ]
  },
  {
    name: 'Joshua Chinwendu',
    description: 'Full Stack Developer. Love working with Python Django framwork.',
    url: 'https://joshualine.hashnode.dev',
    twitter: '@joshchinwendu',
    tags: [
      'JavaScript',
      'Python',
      'Node.js',
      'React',
      'Django',
      'APIs',
      'HTML',
      'CSS',
    ]
  },
  {
    name: 'Omomurewa George-Ashiru',
    description: 'Murewa is a software developer and IT business analyst. She writes technical and career content.',
    url: 'https://blog.murewaashiru.com/',
    twitter: '@rachael_xx',
    tags:[
      'JavaScript',
      'Web Development',
      'Node.js',
      'TypeScript',
      'Project Management',
      'Business Analysis'
    ]
  },
  {
    name: 'Rasmus Langvad',
    description: 'Senior Frontend Developer from Sweden writing about web, tech and mentorship. Currently working with Vue, Nuxt and Node.',
    url: 'https://langvad.dev/blog/',
    twitter: '@rlangvad',
    tags:[
      'JavaScript',
      'Front End',
      'Vue',
      'Nuxt',
      'Node.js',
      'TailwindCSS',
      'Web Development',
      'Storybook',
      'Design System',
      'Mentorship',
    ]
  },
  {
    name: 'Matthew Hart',
    description: 'DevOps focused developer, this is my blog where I discuss solutions I find while I work',
    url: 'https://mattou07.net/',
    twitter: '@mattou07',
    tags:[
      'DevOps',
      'Web Development',
      'C#',
      'Azure',
      'Umbraco',
      'Powershell',
      'IIS',
    ]
  },
  {
    name: 'Ankur Tyagi',
    description: 'Hi, I’m Ankur Tyagi, Software Engineer, Mentor, Coach, Content creator, Checkout my website for more details at https://theankurtyagi.com/',
    url: 'https://theankurtyagi.com/blog/',
    twitter: '@TheAnkurTyagi',
    tags: [
      'Web Development',
      'JavaScript',
      'Python',
      'HTML',
      'React',
      'Freelancing',
      'Mentorship',
      'WordPress',
      'Software Development',
      'Software Architecture',
      'Software Engineering',
      'Software Engineer',
      'Project Management',
      'Front End',
      'CSS',
    ],
  },
  {
    name: 'Mads Brodt',
    description: 'Front-end engineer. Sharing technical tutorials and career advice to help you become a better developer.',
    url: 'https://madsbrodt.com/blog/',
    twitter: '@madsbrodt',
    tags: [
      'JavaScript',
      'Web Development',
      'HTML',
      'CSS',
      'TailwindCSS',
      'React',
      'Vue',
      'Front End',
      'Freelancing',
      'Career'
    ]
  },
  {
    name: 'James Drysdale',
    description: 'Frontend Developer from Scotland writing about web development. Currently working with React, React Native and Node.',
    url: 'https://jamesdrysdale.hashnode.dev/',
    twitter: '@JamesDrysdale84',
    tags:[
      'JavaScript',
      'HTML',
      'CSS',
      'Front End',
      'Web Development',
      'React',
      'React Native',
      'SEO',
    ]
  },
  {
    name: 'Piyush Sinha',
    description: 'Frontend Engineer | Problem Solver',
    url: 'https://piyushsinha.tech/',
    twitter: '@devps2020',
    tags:[
      'JavaScript',
      'Web Development',
      'React',
      'Web Components',
      'Chrome Extension',
    ]
  },
  {
    name: 'Victor Meunier',
    description: 'Software engineer | Gamedev',
    url: 'https://blog.victormeunier.com/',
    twitter: '@VicMeunier',
    tags:[
      'Web',
      'CV',
      'ML',
      'DL',
      'Gamedev',
    ]
  },
  {
    name: 'Saad Ahmad',
    description: 'Frontend developer | Mechanical engineer' ,
    url: 'https://medium.com/@saadahmadhere' ,
    twitter: '@imsaadahmad' ,
    tags: [
      'Github',
      'API',
      'Mongoose',
      'Express',
      'Node.js',
      'Hyper terminal',
    ]
  },
  {
    name: 'Tim Robards',
    description: 'Frontend Developer and creator of easeout.co, a blog/community for web developers and designers alike!',
    url: 'https://easeout.co',
    twitter: '@easeoutco',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'Web Development',       
      'Angular',
      'React',
      'Node.js',      
      'Front End',  
    ]
  },
  {
    name: 'Peter Smulovics',
    description: 'Dad, Geek, Geek Dad - Microsoft enthusiast' ,
    url: 'https://dotneteers.net' ,
    twitter: '@mountgellert' ,
    tags: [
      'Microsoft',
      '.NET',
      'C#',
      'Software Development',
      'Software Architecture',
      'Software Engineering',
      'Software Engineer',
      'Project Management',
      'Mentorship',
    ]
  },
  {
    name: 'Learnedia',
    description: 'WP dev tips and tricks, conversion tracking tips' ,
    url: 'https://learnedia.com/' ,
    twitter: '@helloImLearnrr' ,
    tags: [
      'WordPress',
      'PHP',
      'HTML',
      'CSS',
      'JavaScript',
      'Conversion tracking',
      'GTM',
      'GA',
      'SEO',
    ]
  },
  {
    name: 'Steven Spads',
    description: 'Full-stack Web Developer from Canada. Sharing web development tips, techniques, and tutorials to help you become a better web developer.',
    url: 'https://lumin8media.com',
    twitter: '@stevenspads',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'TypeScript',
      'Angular',
      'React',
      'Node.js',
      'NestJS',
      'Laravel',
      'Web Development',
    ]
  },
  {
    name: 'Emmanuel Ezeka',
    description: 'A frontend web developer, Electrical/Electronics Engineer, Passionate about problem-solving.',
    url: 'https://eecvision.hashnode.dev/',
    twitter: '@EECvision',
    tags: [
      'HTML',
      'CSS',
      'Tailwindcss',
      'JavaScript',
      'React',
      'Node.js',
      'Git',
      'Web Development',
    ]
  },
  {
    name: 'Sebastian Hesse',
    description: 'Serverless Cloud Expert - Blogging about everything related to AWS Cloud, Serverless, Java, Node.js and JavaScript.',
    url: 'https://www.sebastianhesse.de/blog',
    twitter: '@seeebiii',
    tags: [
      'Software Engineer',
      'AWS',
      'Serverless',
      'Cloud Infrastructure',
      'APIs',
      'Java',
      'JavaScript',
      'TypeScript',
      'Node.js',
      'Web Development',
    ]
	},
    {
    name: 'Godswill Umukoro',
    description: 'Software engineer who loves building frontend applications',
    url: 'https://godswillumukoro.hashnode.dev',
    twitter: '@umuks_',
    tags: [
      'Software Engineer',
      'Javascript',
      'React',
      'Node.js',
      'APIs',
      'Web Development',
    ]
	},
];
